### ISSUE TITLE
The 'postgresql_privs' module cannot grant access to database by another role

### ISSUE THREAD

**Issue by drybjed** [ansible-collections/community.postgresql#38]
##### SUMMARY

The `postgresql_privs` role is broken when trying to grant access to a PostgreSQL database owned by one role, to a different PostgreSQL role.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_privs

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = None
  configured module search path = ['/home/drybjed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/drybjed/.local/lib/python3.7/site-packages/ansible
  executable location = /home/drybjed/.local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
Empty output
```

##### OS / ENVIRONMENT

OS: Debian Buster
Database: PostgreSQL 11

##### STEPS TO REPRODUCE

The idea is to create a PostgreSQL "database role" which is an owner of the database itself and cannot be logged in directly. Then, an "application role" is granted access to the "database role", and this allows the application role to access the database without the ability to remove the database itself, or perform other admin-level tasks on it, for security reasons.

```yaml
---

- hosts: 'localhost'
  become: True

  tasks:

    - name: Create database role
      postgresql_user:
        name: "gitlabhq_production"
        role_attr_flags: "NOLOGIN"
        state: present
      become: True
      become_user: 'postgres'

    - name: Create database
      postgresql_db:
        name: "gitlabhq_production"
        owner: 'gitlabhq_production'
        state: present
      become: True
      become_user: 'postgres'

    - name: Create application role
      postgresql_user:
        name: "gitlab"
        state: present
      become: True
      become_user: 'postgres'

    - name: "Grant access to database role by application role"
      postgresql_privs:
        roles: "gitlab"
        type: "group"
        objs: "gitlabhq_production"
        database: "gitlabhq_production"
      become: True
      become_user: 'postgres'
```

##### EXPECTED RESULTS

The `postgres_privs` module should grant access to the `gitlabhq_production` PostgreSQL role by the `gitlab` PostgreSQL role.

##### ACTUAL RESULTS

```paste below
PLAY [localhost] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
ok: [localhost]

TASK [Create database role] ****************************************************************************************************************************
changed: [localhost]

TASK [Create database] *********************************************************************************************************************************
changed: [localhost]

TASK [Create application role] *************************************************************************************************************************
changed: [localhost]

TASK [Grant access from app role to database role] *****************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: |-
    zero-length delimited identifier at or near """"
    LINE 1: GRANT ""gitlabhq_production"" TO "gitlab";
                   ^

```
Output of the failed task with -vvvv debugging enabled:
```
TASK [Grant access from app role to database role] *****************************************************************************************************
task path: /home/drybjed/src/projects/lxc.tycho.drybjed.net/playbooks/test-postgres.yml:31                                                             
The full traceback is:
  File "/tmp/ansible_postgresql_privs_payload_s8jzrx80/ansible_postgresql_privs_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_privs.py", line 1120, in main
  File "/tmp/ansible_postgresql_privs_payload_s8jzrx80/ansible_postgresql_privs_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_privs.py", line 802, in manipulate_privs
fatal: [code]: FAILED! => changed=false 
  invocation:
    module_args:
      ca_cert: null
      database: gitlabhq_production
      fail_on_role: true
      grant_option: null
      host: ''
      login: postgres
      login_host: ''
      login_password: ''
      login_unix_socket: ''
      login_user: postgres
      objs: gitlabhq_production
      password: ''
      port: 5432
      privs: null
      roles: gitlab
      schema: null
      session_role: null
      ssl_mode: prefer
      state: present
      target_roles: null
      trust_input: true
      type: group
      unix_socket: ''
      usage_on_types: true
  msg: |-
    zero-length delimited identifier at or near """"
    LINE 1: GRANT ""gitlabhq_production"" TO "gitlab";
                   ^
```

**Comment by tcraxs** [comment]
!component =postgresql_privs

**Comment by tcraxs** [comment]
bot_status

**Comment by tcraxs** [comment]
The problematic thing is the quoting. I checked this on a local PostgreSQL 13.1:
```
postgres=# GRANT ""gitlabhq_production"" TO "gitlab";
ERROR:  zero-length delimited identifier at or near """"
LINE 1: GRANT ""gitlabhq_production"" TO "gitlab";
              ^
postgres=# GRANT "gitlabhq_production" TO "gitlab";
GRANT ROLE
```

**Comment by tcraxs** [comment]
So it sums up to a forced quoting of an already quoted string in [code line 803](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_privs.py#L803).

**Comment by Andersson007** [comment]
@drybjed thanks for reporting this!
@tcraxsthanks for the investigation, would you like to fix this?

**Comment by Andersson007** [comment]
I had a quick look: if we remove the double quotes, the tests in the part related to names with dots will fail.
I stripped the quotes from a role like this:
```
 802                 else:
 803                     for_whom.append('"%s"' % r.strip('"'))
```
and the current tests pass.
Maybe there are other options how to fix this more gracefully. We definitely should cover the module better

**Comment by Andersson007** [comment]
@drybjed btw, while it's not fixed, you could use `postgresql_user` module with `groups` parameter or `postgresql_membership` module, e.g.:
```
    - name: Create application role
      postgresql_user:
        name: "gitlab"
        groups: "gitlabhq_production"
        state: present
      become: True
      become_user: 'postgres'
```

**Comment by tcraxs** [comment]
> @tcraxsthanks for the investigation, would you like to fix this?

Sorry no time ATM for fixing it

**Comment by Andersson007** [comment]
@tcraxs ok, np!
Hmm, it seems that the case is already covered by integration tests in tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml:
```
1399 - name: Test community.general/issue/1058 GRANT with hyphen
1400   become: yes
1401   become_user: "{{ pg_user }}"
1402   postgresql_privs:
1403     login_user: "{{ pg_user }}"
1404     login_db: "{{ db_name }}"
1405     roles: "test-role"
1406     objs: "{{ pg_user }}"
1407     type: "group"
1408   register: result
```
It works well there and returns:
```
    "queries": [
        "GRANT \"postgres\" TO \"test-role\";"
    ]
```
Ubuntu 18.04, PostgreSQL 10.15.
Strange..
Looking further

**Comment by Andersson007** [comment]
@tcraxs i think line 803 is not the reason.
I think this was already fixed.
```
        if obj_type == 'group':
            set_what = ','.join('"%s"' % i for i in obj_ids)
```
couple of month ago it was changed to
```
        if obj_type == 'group':
            set_what = ','.join(obj_ids)
```
that's why i cannot reproduce it running the tests from `main`. And the mentioned part of tests which covers the case was added when fixing similar case.
@tcraxs could you please try the same playbook after fixing that line like above or using the development version from main or latest collection available on Galaxy?
@drybjed same question to you.

If that's ok, just install the latest version from Galaxy https://galaxy.ansible.com/community/postgresql. How to do it see  [here]( https://docs.ansible.com/ansible/latest/user_guide/collections_using.html)

Waiting for your feedback, thanks!

**Comment by Andersson007** [comment]
I'll close the PR for a while.
@drybjed if you miss the comment above, when you try the latest version, please let me know how it works. Thanks! (we can reopen this issue at any time)

**Comment by drybjed** [comment]
@Andersson007, sorry for missing the comment. I cannot modify the module as you suggest because it's already modified, the [changes](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_privs.py#L775-L776) should be included in Ansible 2.10.5 I'm currently using. The issue is still present.

**Comment by Andersson007** [comment]
@drybjed I reopened the issue, thanks for the feedback. Will see

**Comment by Andersson007** [comment]
@drybjed, i copy-pasted the playbook in the description and ran it with Ansible 2.10.5 (i removed 2.10.1 before installing 2.10.5).
```
[root@test1 ansible]# ansible --version
ansible 2.10.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
Everything works ok:
```
PLAY [all] ***************************************************************************************************************************************

TASK [Create database role] **********************************************************************************************************************
changed: [test1]

TASK [Create database] ***************************************************************************************************************************
changed: [test1]

TASK [Create application role] *******************************************************************************************************************
changed: [test1]

TASK [Grant access to database role by application role] *****************************************************************************************
changed: [test1]

PLAY RECAP ***************************************************************************************************************************************
test1                  : ok=4    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
Maybe there are some things left from the previous installation in your system?
Could you please change `postgresql_privs` to `community.postgresql.postgresql_privs` in your playbook?

**Comment by Andersson007** [comment]
@drybjed no problem! I'm happy we rechecked together and found that everything works as expected:) thanks for the feedback!
